[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_sqlite", "php83Extensions.sqlite3", "php83Extensions.mbstring", "php83Extensions.gd", "php83Extensions.fileinfo"]

[phases.build]
cmds = [
  "mkdir -p database uploads/posts uploads/avatar uploads/projects",
  "chmod -R 777 database uploads"
]

[start]
cmd = "mkdir -p database uploads/posts uploads/avatar uploads/projects && php -S 0.0.0.0:$PORT router.php"
